/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 head_sculpture.glb --types --shadows
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    FBHead: THREE.Mesh;
  };
  materials: {
    FBHead_preview_mat: THREE.MeshStandardMaterial;
  };
};

export function HeadModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "http://localhost:3000/models/head/head_sculpture.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FBHead.geometry}
        material={materials.FBHead_preview_mat}
        scale={0.4}
      />
    </group>
  );
}

useGLTF.preload("./head_sculpture.glb");
